import json

menup = ('Ver listado de pinturas', 'Buscar pintura', 'Agregar pintura', 'Eliminar pintura', 'Exportar pintura')

for ind, opt in enumerate(menup):
    print({ind + 1} , {opt})
    
    ans = (input('Escoje una de estas opciones:'))
    
    if ans == 1:
        pass
    elif ans == 2:
        pass
    elif ans == 3:
        pass
    elif ans == 4:
        pass
    elif ans == 5:
        pass